### ISSUE TITLE
Generate models from json-schema

### ISSUE THREAD

**Issue by smileatom** [tomquist/ReverseJson#4]
Generating models from json data is kind of pointless.  Generate from json-schema instead.

**Comment by tomquist** [comment]
The main purpose of this tool is to infer a data model when there is no specification or schema which unfortunately is often the case in real-world projects. However, there is already work in progress to import swagger specifications which basically uses json-schema but it has some limitations. Once this is finished, it should be easy to create an importer for json-schema. Feel free to open a pull request.
