### ISSUE TITLE
Xcode 10 fails

### ISSUE THREAD

**Issue by 404-HoseNotFound** [tomquist/ReverseJson#5]
**Xcode 10 won't complile Utils.swift...**

**Reason:** 
Voodoo CharRanges are too big for the compiler -> Time out!!!

**Take a look here:**
private static let headCharRanges: [CountableClosedRange<UInt32>]

**Solution:**
A quick fix or hack is to split the array in small arrays and combine them later.

**Note:**
"...Du kannst von Glück sagen, dass ich meine Hose noch an hab" ;-)

**Comment by tomquist** [comment]
Project now builds again on Xcode 10 without the necessity for hosen and wrappers.
